"""SQLite-backed persistence: schema, types, accessors."""

from polymarket_bot.persistence.repo import (
    Fill,
    Market,
    Order,
    Settlement,
    all_open_orders,
    append_equity,
    cancel_order_row,
    equity_curve,
    fills_for_market,
    get_market,
    get_meta,
    insert_fill,
    insert_order,
    insert_settlement,
    inventory_for_market,
    markets_with_unsettled_fills,
    latest_equity,
    list_fills,
    list_settlements,
    open_orders_by_market,
    set_meta,
    settle_market_row,
    update_market_quote,
    settlement_stats,
    unsettled_markets_due,
    update_order_filled,
    upsert_market,
)
from polymarket_bot.persistence.schema import init_db

__all__ = [
    "Market", "Order", "Fill", "Settlement",
    "init_db",
    "upsert_market", "get_market", "settle_market_row", "unsettled_markets_due",
    "insert_order", "open_orders_by_market", "all_open_orders", "update_order_filled",
    "cancel_order_row",
    "insert_fill", "fills_for_market", "list_fills",
    "insert_settlement", "list_settlements", "settlement_stats",
    "inventory_for_market", "markets_with_unsettled_fills",
    "append_equity", "equity_curve", "latest_equity",
    "get_meta", "set_meta",
]
